// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config"; // Added the env import here

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // ADD THIS LINE BELOW: It tells Prisma exactly how to execute your seed file
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Points the Prisma CLI to use your unpooled port 5432 for migrations
    url: env("DIRECT_URL"), 
  },
});